-- CREATE DATABASE DBstore



-- CREATE TABLE Users (
--     id INT PRIMARY KEY IDENTITY(1,1),
--     username NVARCHAR(50) NOT NULL UNIQUE,
--     email NVARCHAR(100) NOT NULL UNIQUE,
--     password NVARCHAR(MAX) NOT NULL,
--     createdAt DATETIME DEFAULT GETDATE(),
--     updatedAt DATETIME DEFAULT GETDATE()
-- );



